# Generated by Django 4.1.7 on 2023-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default=0, max_length=20, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
