# Generated by Django 4.1.7 on 2023-03-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Группа товаров')),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группа товаров',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
