# Generated by Django 4.1.7 on 2023-03-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.productgroup', verbose_name='Группа товаров'),
            preserve_default=False,
        ),
    ]
